### ISSUE TITLE
draft-association: definition of FAA

### ISSUE THREAD

**Issue by mallory** [IRTF-HRPC/drafts#42]
From the HRPC 110 meeting:

*Action: definitions and distinction early in the draft for FAA.*

"I'd like to do that directly on top and show that they're different then we can
discuss them in a combination later because then they are extended and add an
emphasis that the document is about human rights as per the HRPC charter and
not their implementation in national laws."

**Comment by nllz** [comment]
https://github.com/IRTF-HRPC/drafts/commit/cf9980cb62d9d7bf5222b0856fa685e70f62c21d
